# Verificando propriedades de um ndarray

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([6, 1, 5, 6, 2, 0, 9, 9, 9, 8], dtype=int32)

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[ 29,  77,  84,  85,  99],
       [  8,  30,  62,  45,   7],
       [ 14,  32,  38,  97, 100],
       [ 93,  39,  36,   4,  30]], dtype=int32)

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.53138378, 0.13407833, 0.74656382, 0.38063767, 0.51873529],
        [0.98602639, 0.28916677, 0.94781398, 0.73946867, 0.93761358],
        [0.14359921, 0.65668435, 0.461966  , 0.21308303, 0.12150592],
        [0.23022305, 0.36798157, 0.98899022, 0.70160683, 0.94416265]],

       [[0.23695885, 0.62015437, 0.1005821 , 0.99478339, 0.72174445],
        [0.85853427, 0.14426109, 0.81438054, 0.35999277, 0.32852123],
        [0.14824553, 0.66747302, 0.24081752, 0.07765101, 0.53206051],
        [0.48706151, 0.85773193, 0.91197515, 0.48466603, 0.39771946]],

       [[0.8627151 , 0.85319199, 0.98106986, 0.35895817, 0.07321782],
        [0.00715164, 0.82556971, 0.42698002, 0.50243279, 0.89182084],
        [0.87680452, 0.45389554, 0.5132722 , 0.66966984, 0.97704065],
        [0.95072881, 0.04882323, 0.61613162, 0.76457296, 0.81589183]]])

### Verificando o formato e quantidade de dimensões de um array - shape e dim

In [5]:
# A propriedade shape retorna o formato do array
a1D.shape

(10,)

In [6]:
a2D.shape

(4, 5)

In [7]:
a3D.shape

(3, 4, 5)

In [8]:
# A propriedade ndim retorna o números de dimensões do array
a1D.ndim

1

In [9]:
a2D.ndim

2

In [10]:
a3D.ndim

3

### Verificando o tamanho das dimensões de um array - len

In [11]:
len(a1D) # Retorna o tamanho da 1a dimensão (quantidade de colunas)

10

In [12]:
len(a2D) # Retorna o tamanho da 1a dimensão (quantidade de linhas)

4

In [13]:
len(a2D[0]) # Retorna o tamanho da 2a dimensão (quantidade de colunas)

5

In [14]:
len(a3D) # Retorna o tamanho da 1a dimensão (quantidade de páginas)

3

In [15]:
len(a3D[0]) # Retorna o tamanho da 2a dimensão (quantidade de linhas)

4

In [16]:
len(a3D[0][0]) # Retorna o tamanho da 3a dimensão (quantidade de colunas)

5

### Verificando a quantidade de elementos de um array - size

In [17]:
a1D.size

10

In [18]:
a2D.size

20

In [19]:
a3D.size

60

### Verificando o tipo dos elementos um array - dtype

In [20]:
a1D.dtype

dtype('int32')

In [21]:
a1D.dtype.name

'int32'

In [22]:
a2D.dtype

dtype('int32')

In [23]:
a2D.dtype.name

'int32'

In [24]:
a3D.dtype

dtype('float64')

In [25]:
a3D.dtype.name

'float64'